* Making scientific posters in org mode
* Preamble                                                    :ignore:
** org specific settings                                        :ignore:
# ----------------------------------------------------------------------
#+OPTIONS: email:t toc:nil num:nil author:t date:t 
#+STARTUP: align fold
#+SEQ_TODO: TODO(t) | DONE(d)
#+TAGS: figure(f) check(c) noexport(n) ignore(i)
#+LANGUAGE: en
#+EXCLUDE_TAGS: noexport TODO
#+DATE: {{{time(%Y-%m-%d %H:%M)}}}
# ----------------------------------------------------------------------
** Buffer-wide source code blocks                               :ignore:
# ----------------------------------------------------------------------
# Set elisp variables need for nice formatting We want no new lines in
# inline results and a paragraph size of 80 characters Important: this
# has to be evaluated witch C-c C-c in order to work in the current
# buffer
#+BEGIN_SRC emacs-lisp :exports none :results silent

  (require 'ox-md nil t)
  ; set timestamp format
  ;(setq org-export-date-timestamp-format "%FT%T%z")
  (require 'org-wc)
  (flyspell-mode t)
  ;(evil-declare-change-repeat 'company-complete)
  (setq synosaurus-choose-method 'popup)
	(synosaurus-mode t)
	(auto-complete-mode t)
  ;(ac-config-default)
  ;(add-to-list 'ac-modes 'org-mode)
	(linum-mode t)
  (whitespace-mode t)
  (setq org-babel-inline-result-wrap "%s")
	(setq org-export-with-broken-links "mark")
  (setq fill-column 72)
  (setq whitespace-line-column 72)
	;(setq org-latex-caption-above '(table image))
	(setq org-latex-caption-above nil)
	(org-toggle-link-display)
	; don't remove logfiles at export
  (setq org-latex-remove-logfiles nil)
	
  ; Keybindings
  ; (global-set-key (kbd "<f7> c") "#+CAPTION: ")
  (defun setfillcolumn72 ()
	   (interactive)
     (setq fill-column 72)
		 )

  (defun setfillcolumn42 ()
	   (interactive)
     (setq fill-column 42)
   )
  (define-key org-mode-map (kbd "C-c c #") "#+CAPTION: ")
  (define-key org-mode-map (kbd "C-c l #") "#+LATEX_HEADER: ")
  (define-key org-mode-map (kbd "C-c f c 4 2") 'setfillcolumn42)
  (define-key org-mode-map (kbd "C-c f c 7 2") 'setfillcolumn72)
	
  (setq org-odt-category-map-alist
      '(("__Figure__" "*Figure*" "value" "Figure" org-odt--enumerable-image-p)))
 

	; let ess not ask for starting directory
  (setq ess-ask-for-ess-directory nil)

  ;(setq org-latex-pdf-process '("latexmk -pdflatex='xelatex
  ;-output-directory=../output/tex/ -interaction nonstopmode' -pdf
  ;-bibtex -f %f"))
  (setq org-latex-logfiles-extensions 
      (quote("bcf" "blg" "fdb_latexmk" "fls" 
      "figlist" "idx" "log" "nav" "out" "ptc" 
      "run.xml" "snm" "toc" "vrb" "xdv")))

  ; deactivate link resolving
  (setq org-activate-links nil)


#+END_SRC
#
#
#
# ----------------------------------------------------------------------
** End preamble                                                 :ignore:
# ----------------------------------------------------------------------

* Author
Philipp Homan <phoman1 at northwell dot edu>
* Getting Started
This is a simple template to produce a scientific poster with emacs and
org-mode.
 
** Prerequisites
This was developed and tested on a Linux Ubuntu 17.04 machine. To
produce the poster from the command line, GNU emacs and texlive must
be installed together with some additional emacs and texlive
packages. Specifically, the following software and associated libraries
are required:
*** texlive
**** xetex
**** latexmk
*** emacs
**** org-mode
**** ess
**** org-ref

*** R
**** pacman
**** cowplot
**** ggplot2

* Installing
Download the repository and run tar xvfz on the tarball.

* Producing the poster
Change to the org-mode-poster directory and run 'make poster'.

* Built With
src_bash{lsb_release -sd} {{{results(Ubuntu 17.10)}}} on emacs
src_elisp{emacs-version} {{{results(25.2.2)}}} and org-mode
src_elisp{org-version} {{{results(9.1.7)}}}.
